package trader

const (
	textType            = "text"
	imageType           = "image"
	voiceType           = "voice"
	videoType           = "video"
	musicType           = "music"
	newsType            = "news"
	mpnewsType          = "mpnews"
	wxcardType          = "wxcard"
	miniprogrampageType = "miniprogrampage"
	MpVideoType         = "mpvideo"

	AccessTokenURL         = "https://api.weixin.qq.com/cgi-bin/token?grant_type=client_credential&appid="
	UploadURL              = "https://api.weixin.qq.com/cgi-bin/material/add_material?access_token="
	AddNewsURL             = "https://api.weixin.qq.com/cgi-bin/material/add_news?access_token="
	SendMsgURL             = "https://api.weixin.qq.com/cgi-bin/message/custom/send?access_token="
	CreateMenuURL          = "https://api.weixin.qq.com/cgi-bin/menu/create?access_token="
	MaterialURL            = "https://api.weixin.qq.com/cgi-bin/material/"
	TypingURL              = "https://api.weixin.qq.com/cgi-bin/message/custom/typing?access_token="
	KFaccountURL           = "https://api.weixin.qq.com/customservice/kfaccount/"
	SetKfAccountheadimgURL = "http://api.weixin.qq.com/customservice/kfaccount/uploadheadimg?"
	GetkfListURL           = "https://api.weixin.qq.com/cgi-bin/customservice/getkflist?access_token="
	Menu                   = "https://api.weixin.qq.com/cgi-bin/menu/"
	MediaURL               = "https://api.weixin.qq.com/cgi-bin/media/"
	SendAllURL             = "https://api.weixin.qq.com/cgi-bin/message/mass/sendall?access_token="
	DeleteSendALLURL       = "https://api.weixin.qq.com/cgi-bin/message/mass/delete?access_token="
	PreviewURL             = "https://api.weixin.qq.com/cgi-bin/message/mass/preview?access_token="
	SendAllStatusURL       = "https://api.weixin.qq.com/cgi-bin/message/mass/get?access_token="
	MassSpeedURL           = "https://api.weixin.qq.com/cgi-bin/message/mass/speed/"
	TemplateURL            = "https://api.weixin.qq.com/cgi-bin/template/"
	TagsURL                = "https://api.weixin.qq.com/cgi-bin/tags/"
	CommentURL             = "https://api.weixin.qq.com/cgi-bin/comment/"
)
